<?php
session_start();
include 'config/config_1.php';

$obj = new Banco;

include 'topo.php';
?>

<div class="column-1 col-lg-8 col-md-12">
    <h4 class="list-group-item list-group-item-action py-3 lh-tight">Artigos</h4>

    <div class="conteudo">
        Qu&iacute;mica Nova<br>
        Print ISSN 0100-4042<br>
        Qu&iacute;m. Nova vol.22 n.1&nbsp; S&atilde;o Paulo Jan./Feb. 1999<br>
        REVIS&Atilde;O
        <br>
        <br>
        <p><strong>Leila S. R. Brickus# e Francisco R. de Aquino Neto</strong><br>
            LADETEC - Instituto de Qu&iacute;mica - Universidade Federal do Rio de Janeiro - Ilha do Fund&atilde;o - CT - Bloco A - Sala 607 - 21949-900 - Rio de Janeiro - RJ</p>
        <p>Indoor air quality and chemistry. In Brazil, very little experimental work on measurements of indoor air pollutant levels has been done. Nowadays, increasing attention is being given to indoor air quality and the health problems associated with buildings and the indoor work environment. The scope of this paper is to review the major pollutants found in indoor environments and their sources. Subsequently, exposure to indoor air pollutants and health effects are considered. The review concludes by briefly addressing assessment of indoor air quality in Brazil and research needs. </p>
        <p>Keywords: indoor air quality; sick building syndrome; air pollution. </p>
        <div class="subtítuloInterno">1. INTRODU&Ccedil;&Atilde;O </div>
        <p>A qualidade do ar de interiores (QAI) tornou-se um tema de pesquisa importante na &aacute;rea de sa&uacute;de p&uacute;blica nos &uacute;ltimos 15 anos. Esse interesse ocorreu ap&oacute;s a descoberta de que baixas taxas de troca de ar nestes ambientes ocasionam um aumento consider&aacute;vel na concentra&ccedil;&atilde;o de poluentes qu&iacute;micos e biol&oacute;gicos no ar1. Como todos passamos boa parte de nossa vida di&aacute;ria em recintos fechados, seja em casa, no trabalho, no transporte, ou mesmo em locais de lazer, a preocupa&ccedil;&atilde;o com concentra&ccedil;&otilde;es de contaminantes no ar em ambientes internos &eacute; justific&aacute;vel. </p>
        <p>A disciplina que estuda a qualidade do ar de interiores, chamada &quot;Indoor Air Quality&quot;, &eacute; nova, com cerca de 25 anos no mundo e com apenas 5 anos no Brasil. &Eacute; uma nova &aacute;rea de estudo que re&uacute;ne profissionais de diferentes disciplinas, principalmente qu&iacute;micos, microbiologistas, engenheiros, arquitetos e toxicologistas. </p>
        <p>Nessas &uacute;ltimas d&eacute;cadas, houve um grande aumento de queixas relacionadas &agrave; qualidade de ar em locais fechados nos pa&iacute;ses desenvolvidos, principalmente em edif&iacute;cios de microclima artificial. Essas queixas geraram estudos que foram conduzidos em diferentes pa&iacute;ses e per&iacute;odos, indicando que o ar dentro de casa e outros locais fechados pode estar mais polu&iacute;do do que o ar externo nas grandes cidades industrializadas2a-f. </p>
        <p>Ironicamente, o movimento mundial de conserva&ccedil;&atilde;o de energia, desencadeado na dec&aacute;da de 70, contribuiu de uma forma bastante marcante para as preocupa&ccedil;&otilde;es atuais referentes &agrave; qualidade do ar de interiores. Com o intuito de obter uma melhor efici&ecirc;ncia nos aparelhos de refrigera&ccedil;&atilde;o e aquecimento e, com isso, minimizar o consumo de energia, os pr&eacute;dios de escrit&oacute;rios e residenciais (principalmente em pa&iacute;ses desenvolvidos localizados em clima frio) a partir daquela d&eacute;cada, foram constru&iacute;dos visando uma veda&ccedil;&atilde;o t&eacute;rmica mais eficiente, surgindo os chamados pr&eacute;dios selados. </p>
        <p>Paralelamente, houve um grande aumento na diversidade de produtos para forra&ccedil;&atilde;o, acabamento e mobili&aacute;rio, que cont&eacute;m subst&acirc;ncias qu&iacute;micas pass&iacute;veis de serem dispersas no ar de interiores, dispon&iacute;vel no mercado consumidor. Esses materiais, na maioria dos casos, foram desenvolvidos sem uma preocupa&ccedil;&atilde;o com suas emiss&otilde;es. Atualmente, sabe-se que uma das causas do deterioramento da qualidade do ar de interiores &eacute; devida a essa emiss&atilde;o de subst&acirc;ncias qu&iacute;micas, principalmente compostos org&acirc;nicos vol&aacute;teis (COVs), presentes na composi&ccedil;&atilde;o de materiais de constru&ccedil;&atilde;o3, limpeza e mobili&aacute;rio4. </p>
        <p>A combina&ccedil;&atilde;o desses dois fatores pode ocasionar, via de regra, uma baixa qualidade do ar de interiores. Em resumo, a exist&ecirc;ncia de &quot;pr&eacute;dios doentes&quot; coincide com as mudan&ccedil;as no meio ambiente interno, que ocorrem n&atilde;o apenas devido &agrave; introdu&ccedil;&atilde;o de novos produtos de materiais de constru&ccedil;&atilde;o, consumo e mobili&aacute;rio, como tamb&eacute;m &agrave;s trocas arquitet&ocirc;nicas no ambiente interno, com o intuito de economizar energia. </p>
        <p>Esses estudos t&ecirc;m sido realizados principalmente na Europa e nos Estados Unidos. Contudo, a simples compara&ccedil;&atilde;o desses estudos com a realidade brasileira n&atilde;o &eacute; recomend&aacute;vel. No Brasil, diferen&ccedil;as relacionadas a fatores clim&aacute;ticos, s&oacute;cio-econ&ocirc;micos, geogr&aacute;ficos e habitacionais s&atilde;o bastante evidentes. Por exemplo, os pa&iacute;ses desenvolvidos, situados no hemisf&eacute;rio norte, apresentam um clima temperado, ao passo que o Brasil possui um clima predominantemente tropical e subtropical. Somente esta diferen&ccedil;a clim&aacute;tica acarretar&aacute; uma varia&ccedil;&atilde;o consider&aacute;vel na din&acirc;mica dos poluentes atmosf&eacute;ricos nesses dois sistemas. </p>
        <p>Atualmente, no Brasil, est&aacute; havendo uma conscientiza&ccedil;&atilde;o da imprensa n&atilde;o especializada5 sobre a import&acirc;ncia da qualidade do ar de interiores em locais n&atilde;o industriais, tais como escolas, resid&ecirc;ncias, edif&iacute;cios p&uacute;blicos e comerciais. Em meados de 1996, o Governo Federal Brasileiro proibiu o fumo em lugares fechados de uso coletivo, baseado em pesquisas realizadas por ag&ecirc;ncias internacionais. Contudo, essa lei &eacute; bastante simpl&oacute;ria, j&aacute; que induz a pensar que a fuma&ccedil;a do tabaco &eacute; a grande e &uacute;nica culpada da baixa qualidade do ar respirado em locais fechados. </p>
        <p>Apesar do interesse despertado, infelizmente ainda n&atilde;o existe nenhuma medida, tanto do governo federal quanto do estadual, em avaliar o ar, o qual a popula&ccedil;&atilde;o m&eacute;dia brasileira estaria exposta. Na realidade, a discuss&atilde;o em torno das leis que regulamentam a qualidade do ar de interiores (QAI) em nosso pa&iacute;s esconde quest&otilde;es muito mais abrangentes, dentre as quais a formula&ccedil;&atilde;o de conclus&otilde;es precipitadas, geradas antes mesmo das devidas pondera&ccedil;&otilde;es. </p>
        <p>Em resumo, a QAI envolve a combina&ccedil;&atilde;o de v&aacute;rios fatores complexos que est&atilde;o constantemente sofrendo altera&ccedil;&otilde;es. Logo, a avalia&ccedil;&atilde;o e a remedia&ccedil;&atilde;o dos problemas relacionados &agrave; QAI requerem um entendimento das fontes de emiss&atilde;o, da ventila&ccedil;&atilde;o do pr&eacute;dio e das salas, e dos processos que afetam o transporte e o destino dos contaminantes. Juntos, esses processos determinam as concentra&ccedil;&otilde;es finais dos contaminantes que, ap&oacute;s serem detectados e quantificados, possibilitam a avalia&ccedil;&atilde;o da QAI. </p>
        <p>As se&ccedil;&otilde;es seguintes tratar&atilde;o, com maior destaque, das quest&otilde;es referentes aos processos de emiss&otilde;es e destino de poluentes qu&iacute;micos. Contudo, em ambientes climatizados artificialmente, o conhecimento de engenharia de ar condicionado &eacute; sempre muito &uacute;til. De uma maneira geral, em um sistema de ar condicionado central, v&aacute;rias salas s&atilde;o servidas por uma mesma m&aacute;quina (fan-coil) e nem sempre, por ocasi&atilde;o do projeto, essas ter&atilde;o o mesmo tipo de atividade (gerando o mesmo tipo de poluentes). Outro fator complicador &eacute; o rearranjo de ambientes com divis&oacute;rias, sem levar em considera&ccedil;&atilde;o os diferentes pontos de capta&ccedil;&atilde;o do retorno de ar para cada fan-coil. </p>
        <p>A Figura 1 ilustra, de uma maneira simplificada, o mecanismo de transporte, em um sistema de ventila&ccedil;&atilde;o mec&acirc;nica, de poluentes presentes no ar. Atrav&eacute;s desse processo, fontes desconhecidas de emiss&atilde;o, presentes em um determinado local do pr&eacute;dio, podem contaminar toda a &aacute;rea em que atua a unidade de ar condicionado. </p>
        <div class="subtítuloInterno">2. DESENVOLVIMENTO NO BRASIL </div>
        <p>Entre 1965 e 1994, a porcentagem da popula&ccedil;&atilde;o brasileira vivendo em &aacute;reas urbanas cresceu de 46% para 75,5%. Na maioria dos casos, a migra&ccedil;&atilde;o da popula&ccedil;&atilde;o residente em &aacute;reas rurais para &aacute;reas urbanas ocasionou um saturamento da malha rodovi&aacute;ria dos grandes centros urbanos, ocasionando constantes congestionamentos, principalmente nas horas de maior movimento. Esse aumento ocasionou a deteriora&ccedil;&atilde;o da qualidade do ar urbano, refletindo-se na QAI, tendo em vista que o ar interno procede do exterior. </p>
        <p>No in&iacute;cio de 1993 foi realizado o primeiro levantamento brasileiro sobre polui&ccedil;&atilde;o qu&iacute;mica do ar de interiores, operacionalizado pelo Laborat&oacute;rio de Apoio ao Desenvolvimento Tecnol&oacute;gico (LADETEC), do Instituto de Qu&iacute;mica da Universidade Federal do Rio de Janeiro, em coopera&ccedil;&atilde;o com o Laborat&oacute;rio de Aeross&oacute;is e Gases Atmosf&eacute;ricos (LAGA), do Instituto de Qu&iacute;mica da Universidade de S&atilde;o Paulo, S&atilde;o Paulo. Nesse estudo foram avaliados ambientes de escrit&oacute;rio, hot&eacute;is e restaurantes nas cidades do Rio de Janeiro, S&atilde;o Paulo e Campinas6,7,8. A pesquisa detectou n&iacute;veis de v&aacute;rios poluentes acima ou pr&oacute;ximos aos limites fixados pelas legisla&ccedil;&otilde;es internacionais. </p>
        <p>No final de 1995 e durante o ano de 1996, foi realizado o segundo levantamento da QAI no Brasil. Foram avaliados escrit&oacute;rios em pr&eacute;dios administrativos na cidade do Rio de Janeiro e no Museu Nacional de Belas Artes, localizado no centro do Rio. Valores de contaminantes at&eacute; dez vezes maiores do que no ar externo foram encontrados nesses pr&eacute;dios [raz&atilde;o interna/externa de contaminantes (I/E)], indicando um ac&uacute;mulo de poluentes no ar interno, devido primariamente ao fato de o sistema de ar condicionado central operar com baixa troca de ar9,10,11. No museu que possui ventila&ccedil;&atilde;o natural12, a raz&atilde;o interna/externa (I/E) de contaminantes ficou pr&oacute;xima de um, mostrando a import&acirc;ncia de uma ventila&ccedil;&atilde;o natural diluidora na QAI. Esse estudo concorda com outros estudos internacionais que indicam que a ventila&ccedil;&atilde;o deficiente do ar &eacute; a principal causa de problemas de polui&ccedil;&atilde;o em ambientes internos. </p>
        <p>Apesar de QAI ser uma &aacute;rea de pesquisa recente no Brasil, em novembro de 1995 foi institu&iacute;da a Sociedade Brasileira de Meio Ambiente e Controle de Qualidade de Ar de Interiores - &quot;BRASINDOOR&quot; - com o objetivo de promover o interc&acirc;mbio de diferentes especialidades na quest&atilde;o da QAI. </p>
        <p>Paralelamente &agrave; contribui&ccedil;&atilde;o dos qu&iacute;micos na quest&atilde;o da QAI, j&aacute; existe o interesse de outras &aacute;reas interligadas a essa quest&atilde;o. &Eacute; o caso do Sindicato das Ind&uacute;strias de Refrigera&ccedil;&atilde;o, Aquecimento e Tratamento do Ar do Munic&iacute;pio do Rio de Janeiro, que contactou o LADETEC-IQ/UFRJ em 1995, solicitando consultoria e semin&aacute;rios com o intuito de conscientizar seus membros. Existe um grupo na Faculdade de Sa&uacute;de P&uacute;blica da USP realizando estudos referentes &agrave; contamina&ccedil;&atilde;o microbiol&oacute;gica. Na &uacute;ltima confer&ecirc;ncia internacional referente ao assunto &quot;INDOOR AIR'96&quot;, realizado no Jap&atilde;o, foi observada a publica&ccedil;&atilde;o de trabalhos realizados no Brasil por grupos com forma&ccedil;&atilde;o em engenharia civil e arquitetura e urbanismo13. </p>
        <p>A avalia&ccedil;&atilde;o de contaminantes no ar de ambientes residenciais no estado do Rio de Janeiro faz parte do nosso pr&oacute;ximo projeto nesta &aacute;rea. At&eacute; o presente momento, apenas dois levantamentos de exposi&ccedil;&atilde;o ao rad&ocirc;nio foram efetuados em ambientes residenciais no Brasil14,15. Levando-se em conta que um brasileiro t&iacute;pico gasta no m&iacute;nimo 12 horas do seu tempo di&aacute;rio no ambiente dom&eacute;stico (considerando, por exemplo, um indiv&iacute;duo que sai de casa para o trabalho &agrave;s 6 h e chega do trabalho &agrave;s 18h), torna-se de consider&aacute;vel import&acirc;ncia a avalia&ccedil;&atilde;o da qualidade do ar em resid&ecirc;ncias urbanas brasileiras t&iacute;picas, com o intuito de um mapeamento dos n&iacute;veis de contaminantes encontrados em tais ambientes. </p>
        <p>Atualmente, o Centro de Estudos da Sa&uacute;de do Trabalhador e Ecologia Humana (CESTEH), da Funda&ccedil;&atilde;o Oswaldo Cruz, est&aacute; desenvolvendo um programa de estudos da Qualidade do Ar de Interiores. Um dos principais objetivos desse programa &eacute; promover o interc&acirc;mbio dessa &aacute;rea de pesquisa entre diferentes grupos brasileiros, atrav&eacute;s de estudos inter-institucionais. </p>
        <div class="subtítuloInterno">3. FONTES, TIPOS E INDICADORES DE POLUI&Ccedil;&Atilde;O</div>
        <p>As pr&oacute;prias pessoas e suas respectivas atividades ocupacionais s&atilde;o um dos maiores contribuintes para a polui&ccedil;&atilde;o do ar em ambientes fechados. N&atilde;o apenas pela libera&ccedil;&atilde;o de di&oacute;xido de carbono atrav&eacute;s da respira&ccedil;&atilde;o, ou de subst&acirc;ncias qu&iacute;micas pela transpira&ccedil;&atilde;o, mas tamb&eacute;m pelo transporte de microorganismos (bact&eacute;rias, fungos, v&iacute;rus e &aacute;caros). Al&eacute;m disso, o h&aacute;bito de fumar somado ao desempenho de fun&ccedil;&otilde;es, como pintar, cozinhar e limpar, contribuem para a din&acirc;mica de polui&ccedil;&atilde;o do ar nesse tipo de ambiente16,17. </p>
        <p>A rigor, pode-se dividir os tipos de poluentes em: materiais particulados, aeross&oacute;is, vapores e gases. Esses, por sua vez, podem ser classificados em org&acirc;nicos, inorg&acirc;nicos e biol&oacute;gicos (Tabela 1). Fontes t&iacute;picas de polui&ccedil;&atilde;o do ar, nesse tipo de sistema, incluem materiais de constru&ccedil;&atilde;o, de acabamento e de escrit&oacute;rios. Itens como, carpetes, m&oacute;veis, roupas e tapetes n&atilde;o somente liberam fibras, formalde&iacute;do e outras subst&acirc;ncias qu&iacute;micas, como tamb&eacute;m fornecem ambiente prop&iacute;cio para a prolifera&ccedil;&atilde;o de agentes biol&oacute;gicos, tais como bact&eacute;rias, fungos e &aacute;caros (Fig. 2). Simples processos de limpeza, como varrer, aspirar e espanar a poeira, normalmente removem as part&iacute;culas grandes. Entretanto, freq&uuml;entemente aumentam, por ressuspens&atilde;o, a concentra&ccedil;&atilde;o de part&iacute;culas pequenas no ar. </p>
        <p>Indicadores relacionados &agrave; QAI s&atilde;o fatores que potencialmente causam18,19,20 (ou est&atilde;o associados a outros fatores que causam) a chamada S&iacute;ndrome do Edif&iacute;cio Doente (SED; se&ccedil;&atilde;o IV). Estes indicadores podem ser usados para identificar fontes de polui&ccedil;&atilde;o, determinar falhas no sistema de ventila&ccedil;&atilde;o e de ar condicionado, e correlacionar sintomas dos ocupantes com a qualidade do ar. Os indicadores mais comuns da QAI s&atilde;o: concentra&ccedil;&otilde;es de contaminantes, velocidades de emiss&atilde;o das fontes, velocidades de ventila&ccedil;&atilde;o do ar, odor e percep&ccedil;&atilde;o sensorial, raz&atilde;o de concentra&ccedil;&atilde;o interna/externa e densidade ocupacional. </p>
        <p>Dentre os contaminantes usualmente monitorados est&atilde;o o di&oacute;xido de carbono (CO 2), o mon&oacute;xido de carbono (CO), os compostos org&acirc;nicos vol&aacute;teis totais e especiados, os compostos org&acirc;nicos semi-vol&aacute;teis, o rad&ocirc;nio, a mat&eacute;ria particulada, a nicotina, e as concentra&ccedil;&otilde;es total e espec&iacute;fica de microorganismos21.22. A polui&ccedil;&atilde;o do ar de interiores por aeross&oacute;is alerg&ecirc;nicos tem sido cada vez mais reconhecida como causa de sintomas respirat&oacute;rios23. A quantifica&ccedil;&atilde;o de al&eacute;rgenos espec&iacute;ficos para &aacute;caros e fungos, em ar de recintos fechados, forneceria informa&ccedil;&otilde;es importantes para entender a problem&aacute;tica da SED. Infelizmente, a caracteriza&ccedil;&atilde;o de indicadores confi&aacute;veis ainda &eacute; problem&aacute;tica, especialmente para fungos, uma vez que n&atilde;o somente o cultivo e prepara&ccedil;&atilde;o de extratos, como a pr&oacute;pria padroniza&ccedil;&atilde;o, s&atilde;o bastante vari&aacute;veis entre os laborat&oacute;rios24,25.</p>
        <p>Dentro desse contexto, geralmente s&atilde;o feitos v&aacute;rios tipos de determina&ccedil;&otilde;es de diferentes classes de contaminantes. Isso &eacute; necess&aacute;rio devido &agrave; presen&ccedil;a de diversas fontes de emiss&atilde;o, somadas &agrave;s diferen&ccedil;as nos processos de transporte e destino dos contaminantes. Por exemplo, concentra&ccedil;&otilde;es de COVs e COSVs podem ter pouca correla&ccedil;&atilde;o com concentra&ccedil;&otilde;es de fungos. Similarmente, os COVs podem ter pouca correla&ccedil;&atilde;o entre si, devido a fontes diferentes de emiss&atilde;o; por exemplo, emiss&atilde;o de hidrocarbonetos alif&aacute;ticos por tinta, formalde&iacute;do por resinas, etc. </p>
        <p>Os fatos supra-mencionados demonstram que a determina&ccedil;&atilde;o pura e simples de um &uacute;nico contaminante n&atilde;o serve como indicador global do problema da QAI. </p>
        <div class="subtítuloInterno">3.1. Mat&eacute;ria Particulada </div>
        <p>Mat&eacute;ria particulada &eacute; a forma mais vis&iacute;vel de polui&ccedil;&atilde;o do ar, e &eacute; razoavelmente f&aacute;cil de se determinar quantitativamente com instrumenta&ccedil;&atilde;o m&iacute;nima. O termo mat&eacute;ria particulada total (MPT) refere-se &agrave; mat&eacute;ria total, em fase l&iacute;quida e/ou s&oacute;lida no ar, que &eacute; colet&aacute;vel. Mat&eacute;ria particulada inal&aacute;vel (MPI) refere-se somente &agrave;quelas part&iacute;culas que s&atilde;o pequenas o bastante para passar pelas vias a&eacute;reas superiores e alcan&ccedil;ar o pulm&atilde;o (Fig. 3). Contudo, existe, ainda, muita controv&eacute;rsia relacionada ao tamanho de part&iacute;cula que &eacute; depositada no aparelho respirat&oacute;rio. Enquanto se discute a faixa de tamanho de part&iacute;cula que consegue atingir as diferentes partes do aparelho respirat&oacute;rio, a medida de mat&eacute;ria particulada inal&aacute;vel, por sua vez, &eacute; muito importante, pois parte do que &eacute; inalado pode ser irreversivelmente depositado nas vias respirat&oacute;rias. </p>
        <p>Os di&acirc;metros das part&iacute;culas determinam o seu destino, isto &eacute;, se elas se depositar&atilde;o em superf&iacute;cies horizontais e verticais, se ficar&atilde;o suspensas no ar, ou se ser&atilde;o removidas por filtros de ar condicionado ou aspiradores &agrave; v&aacute;cuo. E, uma vez inaladas, se ser&atilde;o removidas pelas vias a&eacute;reas superiores ou se ir&atilde;o atingir os alv&eacute;olos e depositar-se irreversivelmente (Fig. 3). A composi&ccedil;&atilde;o qu&iacute;mica da mat&eacute;ria particulada no ar, em ambientes fechados, &eacute; altamente vari&aacute;vel, constituindo-se de esporos de mofo, amianto, fibras sint&eacute;ticas, restos de insetos e comida, p&oacute;len, aeross&oacute;is de produtos de consumo (desodorante, fixador de cabelos) e al&eacute;rgenos26. Portanto, o conhecimento da composi&ccedil;&atilde;o da mat&eacute;ria particulada de um determinado ambiente possibilitar&aacute; a previs&atilde;o de efeitos espec&iacute;ficos que sejam adversos &agrave; sa&uacute;de. </p>
        <p>Existem v&aacute;rios mecanismos pelos quais as part&iacute;culas do ar em recintos fechados podem ser produzidas, ou tornar-se a&eacute;reas27. O atrito entre partes que se movimentam ou peda&ccedil;os de m&oacute;veis produzir&atilde;o part&iacute;culas s&oacute;lidas; varrer, tirar a poeira, ou limpar utilizando aspira&ccedil;&atilde;o &agrave; v&aacute;cuo facilita a reentrada de part&iacute;culas s&oacute;lidas no ar; umidificadores e v&aacute;rios tipos de &quot;sprays&quot; produzem part&iacute;culas l&iacute;quidas28. O ato de fumar, ou mesmo cozinhar, produz a condensa&ccedil;&atilde;o de aeross&oacute;is, tanto s&oacute;lidos, como l&iacute;quidos, bem como o simples acionar da descarga de banheiros. </p>
        <p>Os problemas causados por part&iacute;culas, al&eacute;m daqueles relacionados &agrave; sa&uacute;de, incluem deposi&ccedil;&atilde;o nas superf&iacute;cies29, resultando em ch&atilde;o e janelas sujas, estragos nas m&aacute;quinas de precis&atilde;o, dep&oacute;sito de sujeira, descolora&ccedil;&atilde;o de obras de arte em museus, etc. </p>
        <div class="subtítuloInterno">3.2. Rad&ocirc;nio </div>
        <p>O rad&ocirc;nio &eacute; um g&aacute;s radioativo produzido pelo decaimento do elemento qu&iacute;mico r&aacute;dio. Esse g&aacute;s est&aacute; presente nos solos, &aacute;guas fre&aacute;ticas, e em in&uacute;meros materiais de constru&ccedil;&atilde;o, tais como concreto, pedras e tijolos22. Os mecanismos de penetra&ccedil;&atilde;o em recintos fechados variam enormemente. O rad&ocirc;nio origin&aacute;rio do solo pode entrar em recintos fechados atrav&eacute;s de fissuras e rachaduras localizadas no alicerce do pr&eacute;dio, paredes e lajes. Paralelamente, materiais de constru&ccedil;&atilde;o de origem natural, tais como tijolo de argila, m&aacute;rmore e arenito, variam amplamente em concentra&ccedil;&atilde;o de rad&ocirc;nio, e o n&iacute;vel de rad&ocirc;nio em ambientes fechados pode aumentar consideravelmente pela emiss&atilde;o a partir desses materiais. A Ag&ecirc;ncia de Prote&ccedil;&atilde;o Ambiental dos Estados Unidos (U. S. EPA) tem estimado que a concentra&ccedil;&atilde;o de rad&ocirc;nio em milh&otilde;es de resid&ecirc;ncias nos Estados Unidos &eacute; maior que o n&iacute;vel recomendado de 4 pCi/L, e classifica esse g&aacute;s como um dos principais poluentes em recintos fechados, pois representa um s&eacute;rio risco &agrave; sa&uacute;de da popula&ccedil;&atilde;o30. Por outro lado, esse limite &eacute; discut&iacute;vel e varia de pa&iacute;s para pa&iacute;s. No Canad&aacute;, por exemplo, o n&iacute;vel m&aacute;ximo recomendado &eacute; de 20 pCi/L. Segundo STONE31, um estudo realizado em resid&ecirc;ncias canadenses n&atilde;o encontrou nenhuma rela&ccedil;&atilde;o entre n&iacute;veis de rad&ocirc;nio e c&acirc;ncer no pulm&atilde;o. No Brasil, existem alguns poucos trabalhos realizados sobre o problema do rad&ocirc;nio na atmosfera e em materiais de constru&ccedil;&atilde;o14,15. </p>
        <div class="subtítuloInterno">3.3. Compostos Org&acirc;nicos </div>
        <p>S&atilde;o os que apresentam maior variedade. Em sua maioria, s&atilde;o considerados in&oacute;cuos quando em concentra&ccedil;&otilde;es baixas. Contudo, existem pessoas que, com o passar do tempo, desenvolvem uma sensibilidade a um determinado composto qu&iacute;mico. As principais classes de compostos com potencial mutag&ecirc;nico s&atilde;o as N-nitrosaminas, alde&iacute;dos e hidrocarbonetos insaturados e/ou arom&aacute;ticos. A rea&ccedil;&atilde;o de compostos org&acirc;nicos com NO2, gerado pela queima de tabaco e processos de combust&atilde;o, pode acarretar num acr&eacute;scimo adicional de compostos org&acirc;nicos nitrados com potencial mutag&ecirc;nico32. </p>
        <div class="subtítuloInterno">3.3.1. Compostos Org&acirc;nicos Vol&aacute;teis </div>
        <p>A evapora&ccedil;&atilde;o de COVs oriundos de materiais de constru&ccedil;&atilde;o, acabamento, decora&ccedil;&atilde;o e de mobili&aacute;rio, &eacute; uma das principais fontes de COVs em recintos fechados33. Outras fontes importantes s&atilde;o os processos de combust&atilde;o e emiss&otilde;es metab&oacute;licas de microorganismos34. Contribuem ainda para agravar o quadro, os processos que melhoram o transporte desses compostos para a fase vapor35, tais como umidificadores, uso de produtos &agrave; base de aerossol36 e at&eacute; mesmo os sistemas de ar condicionado, supostamente purificadores e condicionadores de ar, que podem ser uma das causas principais de polui&ccedil;&atilde;o no ar interno37. </p>
        <p>Como fontes comuns de COVs em ambientes fechados podemos citar os materiais de constru&ccedil;&atilde;o do pr&oacute;prio pr&eacute;dio, o sistema de ar condicionado, os produtos de consumo utilizados para manuten&ccedil;&atilde;o e cuidados pessoais, m&oacute;veis e decora&ccedil;&atilde;o, e a incurs&atilde;o de ar externo. Atividades espec&iacute;ficas como fumar cigarros e tirar fotoc&oacute;pias contribuem com um acr&eacute;scimo de COVs38. Cada uma dessas fontes citadas faz com que os COVs em ambientes fechados sejam altamente vari&aacute;veis, tornando dif&iacute;cil a detec&ccedil;&atilde;o da fonte. Em outras palavras, as fontes de COVs s&atilde;o numerosas, e uma fonte relativamente pequena pode ocasionar um grande impacto na qualidade do ar, devido a baixos fatores de dilui&ccedil;&atilde;o, ou seu alto grau de toxidez. </p>
        <p>Alguns COVs s&atilde;o relacionados a uma ou outra fonte principal, tais como formalde&iacute;do e clorof&oacute;rmio. A maior fonte do formalde&iacute;do s&atilde;o os produtos de madeira, com ou sem acabamento, com resina de ur&eacute;ia-formalde&iacute;do. O clorof&oacute;rmio &eacute; amplamente introduzido em ambientes fechados devido ao simples ato de tomar banho ou abrir a torneira dom&eacute;stica de &aacute;gua39. </p>
        <div class="subtítuloInterno">3.3.2. Compostos Org&acirc;nicos Semi-Vol&aacute;teis </div>
        <p>Quando um composto org&acirc;nico semi-vol&aacute;til (COSV) &eacute; emitido para o ar, talvez a parti&ccedil;&atilde;o vapor-part&iacute;cula seja o processo f&iacute;sico-qu&iacute;mico mais importante que governa o destino do composto. De fato, a extens&atilde;o na qual a parti&ccedil;&atilde;o ocorre desempenhar&aacute; um papel fundamental na determina&ccedil;&atilde;o da import&acirc;ncia relativa de deposi&ccedil;&atilde;o &uacute;mida, isto &eacute;, condensa&ccedil;&atilde;o de vapores, ou deposi&ccedil;&atilde;o seca. Existe, portanto, um interesse consider&aacute;vel em saber a maneira pela qual um determinado composto distribui-se entre as fases vapor e particulada40,41,42. </p>
        <p>Os hidrocarbonetos polic&iacute;clicos arom&aacute;ticos (HPAs), variando em tamanho desde naftaleno (2 an&eacute;is) a coroneno (6 an&eacute;is), t&ecirc;m sido detectados em ambientes fechados. Os mais mencionados s&atilde;o o naftaleno e seus derivados metilados, antraceno e fenantreno, benzo[a]pireno e benzo[e]pireno, dibenzo[a,b]antraceno, benzo [g,h,i]perileno, indeno[1,2,3-cd]pireno e coroneno. O interesse em HPAs cresceu em 1978 quando Pitts et al. 43 demostraram que os HPA podem reagir com NOx para formar nitroarenos. A partir dessa data grandes esfor&ccedil;os tem sido feitos, para detectar essa classe de composto no meio ambiente. </p>
        <p>Os COSV s&atilde;o encontrados em emiss&otilde;es veiculares (especialmente ve&iacute;culos movidos a diesel), mas tamb&eacute;m nos cartuchos de fotocopiadoras, queima de madeira e tabaco. Estudos que visam a determina&ccedil;&atilde;o da concentra&ccedil;&atilde;o de HPAs como agentes carcinog&ecirc;nicos, freq&uuml;entemente determinam concentra&ccedil;&otilde;es de benzo[a]pireno e /ou &quot;HPAs total&quot;44. A determina&ccedil;&atilde;o de benzo[a]pireno &eacute; muito importante, pois este composto exibe atividade carcinog&ecirc;nica alta em testes com animais e &eacute; considerado um prov&aacute;vel agente carcinog&ecirc;nico em seres humanos45. </p>
        <div class="subtítuloInterno">3.4. Queima do Tabaco </div>
        <p>A fuma&ccedil;a de tabaco cont&eacute;m milhares de constituintes qu&iacute;micos, e ela pode ser, em casos extremos, a maior fonte de mat&eacute;ria particulada respir&aacute;vel do ar em recintos fechados. Portanto, a queima de tabaco produz uma mistura complexa de poluentes, muitos dos quais s&atilde;o irritantes respirat&oacute;rios46,47. </p>
        <p>Sabe-se que concentra&ccedil;&otilde;es altas de fuma&ccedil;a de tabaco incomodam e irritam os indiv&iacute;duos, e que existe uma preocupa&ccedil;&atilde;o com rela&ccedil;&atilde;o aos efeitos potenciais na sa&uacute;de48. Portanto, onde existe alta incid&ecirc;ncia de fumantes e m&iacute;nima ventila&ccedil;&atilde;o pode haver ac&uacute;mulo da fuma&ccedil;a do tabaco, causando irrita&ccedil;&atilde;o, particularmente no sistema respirat&oacute;rio superior. </p>
        <p>De todos os constituintes da fuma&ccedil;a do cigarro encontrados no ar, somente a nicotina, e outros alcal&oacute;ides derivados da nicotina, algumas nitrilas, e alguns derivados da graxa da folha do tabaco, s&atilde;o fornecidos, quase que exclusivamente, pela fuma&ccedil;a do tabaco. A nicotina (I), uma piridina substitu&iacute;da na posi&ccedil;&atilde;o 3 pela N-metilpirrolidina, &eacute; um alcal&oacute;ide da Nicotiana tabacum; &eacute; o principal alcal&oacute;ide do tabaco. Durante o processo de fumar o cigarro, o tabaco queimado emite nicotina para a atmosfera. Em ar de recintos fechados, a nicotina &eacute; considerada o constituinte principal da fuma&ccedil;a do cigarro. Devido a sua alta afinidade por superf&iacute;cies, a nicotina na fase vapor decai mais rapidamente que os outros constituintes da fuma&ccedil;a de cigarro49. Essa particularidade faz com que a nicotina n&atilde;o seja considerada um marcador ideal para processos de queima do tabaco. Contudo, enquanto se pesquisa um melhor marcador, o monitoramento da nicotina em ar de recintos fechados &eacute; uma pr&aacute;tica aceit&aacute;vel. </p>
        <p>Com rela&ccedil;&atilde;o &agrave;s atividades fisiol&oacute;gicas, a nicotina &eacute; t&oacute;xica quando inalada, causando estresse excessivo nos sistemas circulat&oacute;rio e nervoso, e tem sido relacionada ao aumento da suscetibilidade para o desenvolvimento de c&acirc;ncer50. O Instituto Nacional para a Seguran&ccedil;a e Sa&uacute;de Ocupacional dos EEUU (NIOSH) estabeleceu um TLV para nicotina em local de trabalho de 0,5 mg/m351. </p>
        <p>Em 1996, o governo brasileiro proibiu o fumo em locais p&uacute;blicos, o que n&atilde;o impediu que os ocupantes ainda fumassem em tais locais. Recentemente, o Instituto Nacional do C&acirc;ncer (INCa) apresentou um relat&oacute;rio indicando que a grande mortalidade devida ao c&acirc;ncer do pulm&atilde;o est&aacute; relacionada ao fumo (11. 950 mortes). </p>
        <div class="subtítuloInterno">3.5. Oxidantes </div>
        <p>Tem havido um interesse consider&aacute;vel em se determinar a concentra&ccedil;&atilde;o de oxidantes no ar de interiores52. Simulando as condi&ccedil;&otilde;es do ar em ambientes internos, ZHANG et al.53 mostraram rea&ccedil;&otilde;es de O3 e NO2 com COVs insaturados, formando alde&iacute;dos e &aacute;cidos org&acirc;nicos. Sabe-se que o oz&ocirc;nio &eacute; um agente oxidante muito poderoso; esse g&aacute;s reage rapidamente com certas classes de compostos org&acirc;nicos, especialmente aquelas que cont&eacute;m liga&ccedil;&atilde;o insaturada carbono-carbono, gerando alde&iacute;dos e/ ou cetonas. Al&eacute;m de rea&ccedil;&otilde;es em fase gasosa, o oz&ocirc;nio participa tamb&eacute;m de rea&ccedil;&otilde;es em meio heterog&ecirc;neo (exemplo, oz&ocirc;nio e borracha), gerando uma s&eacute;rie de produtos de oxida&ccedil;&atilde;o54 e, conseq&uuml;entente, causando a deteriora&ccedil;&atilde;o de materiais de constru&ccedil;&atilde;o e mobili&aacute;rio dos recintos fechados. </p>
        <p>Este mesmo oz&ocirc;nio &eacute; gerado usualmente, em pequena quantidade, por m&aacute;quinas fotocopiadoras55 e impressoras a laser. Recentemente, Andersson et al.56 mostraram a rea&ccedil;&atilde;o entre estireno e oz&ocirc;nio em equipamento de ventila&ccedil;&atilde;o simulada. A rea&ccedil;&atilde;o foi realizada num tempo de 23 segundos, tempo esse suficientemente razo&aacute;vel para o ar externo passar atrav&eacute;s dos dutos de ar de um determinado pr&eacute;dio, mostrando que a mesma rea&ccedil;&atilde;o entre COVs e oz&ocirc;nio &eacute; poss&iacute;vel em condi&ccedil;&otilde;es ambientais reais. </p>
        <p>J&aacute; o oxig&ecirc;nio, por sua vez, pode interagir com subst&acirc;ncias reativas e / ou luz, formando esp&eacute;cies reativas, tais como di&oacute;xido de nitrog&ecirc;nio, oxig&ecirc;nio singlete57, super&oacute;xido, per&oacute;xido de hidrog&ecirc;nio e per&oacute;xidos org&acirc;nicos. Esses transientes podem desempenhar um papel importante em rea&ccedil;&otilde;es redox, em atmosfera de ambientes fechados. </p>
        <p>Outro g&aacute;s freq&uuml;entemente encontrado tanto em ar externo quanto interno &eacute; o di&oacute;xido de nitrog&ecirc;nio. Esse g&aacute;s oxidante &eacute; normalmente produzido por processos de combust&atilde;o. Segundo Samet et al.58, a U. S. E. P. A. estabeleceu como concentra&ccedil;&atilde;o m&aacute;xima anual m&eacute;dia permitida de NO2 na atmosfera o valor de 53 ppb. </p>
        <p>Atualmente, existem v&aacute;rios estudos sendo publicados tratando da problem&aacute;tica da presen&ccedil;a de agentes oxidantes na forma&ccedil;&atilde;o/transforma&ccedil;&atilde;o de contaminantes no ar de recintos fechados59a-b,60. Essa nova tend&ecirc;ncia de pesquisa torna o estudo do ar de interiores ainda mais atraente. </p>
        <div class="subtítuloInterno">3.6. Contaminantes externos </div>
        <p>No Brasil, onde a ventila&ccedil;&atilde;o do ambiente geralmente &eacute; feita deixando-se as janelas abertas, a polui&ccedil;&atilde;o do ar externo, principalmente por fuma&ccedil;a de ve&iacute;culos e emiss&otilde;es industriais, &eacute; o principal determinante da qualidade do ar de interiores, tanto em resid&ecirc;ncias como em escrit&oacute;rios e casas comerciais situados pr&oacute;ximos ao n&iacute;vel da rua61. A qualidade do ar externo &eacute; de import&acirc;ncia &oacute;bvia na qualidade do ar interno. Se o ar externo n&atilde;o &eacute; de boa qualidade, o ar interno dificilmente ser&aacute; bom. Nesses casos, o ar externo deveria ser limpo atrav&eacute;s dos equipamentos de ventila&ccedil;&atilde;o, antes de entrar no ambiente fechado. Entretanto, medidas s&eacute;rias deveriam ser tomadas a fim de se reduzir a polui&ccedil;&atilde;o do ar urbano. </p>
        <p>As emiss&otilde;es de COVs por ve&iacute;culos desempenham um papel importante na forma&ccedil;&atilde;o do &quot;smog&quot; fotoqu&iacute;mico, que tem ocorrido em &aacute;reas urbanas populosas no mundo inteiro62. O &quot;smog&quot; fotoqu&iacute;mico &eacute; uma mistura de poluentes secund&aacute;rios tais como oz&ocirc;nio, di&oacute;xido de nitrog&ecirc;nio, &aacute;cido n&iacute;trico, alde&iacute;dos e outros compostos org&acirc;nicos, formados a partir de rea&ccedil;&otilde;es fotol&iacute;ticas entre di&oacute;xido de nitrog&ecirc;nio e hidrocarbonetos63. Portanto, a queima de combust&iacute;vel por ve&iacute;culos &eacute; uma das maiores fontes de poluentes em &aacute;reas urbanas, da qual uma boa porcentagem migra para os pr&eacute;dios, contribuindo para a polui&ccedil;&atilde;o do ar interno64. </p>
        <p>V&aacute;rios estudos t&ecirc;m demonstrado que a qualidade do ar externo tem um impacto significativo no ar interno. FIELD et al. 65 monitoraram uma ampla variedade de poluentes no ar tanto interno quanto externo durante uma invers&atilde;o t&eacute;rmica em Londres. Foi observado, nesse estudo, que porcentagens significativas de concentra&ccedil;&atilde;o de COVs espec&iacute;ficos encontrados no ar externo estavam presentes no ar interno. </p>
        <p>Apesar da import&acirc;ncia do conhecimento da composi&ccedil;&atilde;o de poluentes na atmosfera urbana, existem poucos estudos relacionados a esse problema no Brasil66,67,68. Grande parte desses estudos foram realizados no eixo Rio-S&atilde;o Paulo, tendo como principal objetivo estudos de n&iacute;veis de alde&iacute;dos em atmosferas urbanas brasileiras. Esse interesse se deve, em parte, &agrave; utiliza&ccedil;&atilde;o de etanol como combust&iacute;vel alternativo no pa&iacute;s69a-d,70. Ainda assim, existem muitas lacunas a serem preenchidas, e existe uma necessidade imediata de estudos mais sistem&aacute;ticos relacionando &agrave; intera&ccedil;&atilde;o de diferentes poluentes na atmosfera urbana tropical. Lamentavelmente, apesar do Brasil estar localizado em uma regi&atilde;o tropical, n&atilde;o existe nenhum grupo de pesquisa brasileiro estudando os efeitos fotoqu&iacute;micos em atmosfera tropical. Em resumo, o estudo da polui&ccedil;&atilde;o atmosf&eacute;rica no Brasil ainda &eacute; pouco desenvolvido e aquele relacionado &agrave; QAI, praticamente inexistente6-12. </p>
        <div class="subtítuloInterno">4. S&Iacute;NDROME DO EDIF&Iacute;CIO DOENTE</div>
        <p>A baixa qualidade do ar de interiores t&ecirc;m sido relacionada a um n&uacute;mero de efeitos adversos &agrave; sa&uacute;de humana, levando a Organiza&ccedil;&atilde;o Mundial da Sa&uacute;de (OMS) a classificar a S&iacute;ndrome do Edif&iacute;cio Doente como um problema de sa&uacute;de p&uacute;blica. O termo S&iacute;ndrome do Edif&iacute;cio Doente (SED) &eacute; utilizado para descrever situa&ccedil;&otilde;es nas quais os ocupantes de um determinado edif&iacute;cio experimentam efeitos adversos &agrave; sa&uacute;de e ao conforto. Esses efeitos parecem estar vinculados ao tempo de perman&ecirc;ncia no edif&iacute;cio, mas nenhuma doen&ccedil;a espec&iacute;fica, ou causa, pode ser identificada. As reclama&ccedil;&otilde;es podem estar localizadas em uma determinada &aacute;rea ou sala, ou podem estar disseminadas por todo o edif&iacute;cio. Esse tipo de s&iacute;ndrome ocorre principalmente em edif&iacute;cios selados, embora tamb&eacute;m tenha sido observada em edif&iacute;cios que s&atilde;o ventilados naturalmente. A SED &eacute; um problema mundial, e a circula&ccedil;&atilde;o mec&acirc;nica do ar parece ser um fator bastante importante na sua preval&ecirc;ncia. Milh&otilde;es de pessoas, no mundo inteiro, trabalham em locais onde a ventila&ccedil;&atilde;o &eacute; regulada atrav&eacute;s de sistema de circula&ccedil;&atilde;o mec&acirc;nica do ar71,72. </p>
        <p>Segundo a Organiza&ccedil;&atilde;o Mundial de Sa&uacute;de (OMS), a SED &eacute; causada por emiss&otilde;es de contaminantes por fontes de v&aacute;rias origens, isoladas ou associadas, e pode produzir diversos sintomas. Essas condi&ccedil;&otilde;es ambientais adversas produzem altas taxas de absente&iacute;smo e consider&aacute;vel redu&ccedil;&atilde;o dos n&iacute;veis de produtividade do trabalhador. Os sintomas decorrentes da s&iacute;ndrome podem estar ligados a poluentes de origem qu&iacute;mica ou biol&oacute;gica. </p>
        <p>As pessoas podem reclamar de um ou mais dos seguintes sintomas: irrita&ccedil;&atilde;o e obstru&ccedil;&atilde;o nasal; desidrata&ccedil;&atilde;o e irrita&ccedil;&atilde;o da pele, ocasionalmente associada a rachaduras na superf&iacute;cie da pele exposta ao ambiente; irrita&ccedil;&atilde;o e secura na garganta; irrita&ccedil;&atilde;o e sensa&ccedil;&atilde;o de secura nas membranas dos olhos; dor de cabe&ccedil;a, letargia e cansa&ccedil;o generalizado, levando &agrave; perda de concentra&ccedil;&atilde;o. Normalmente, esses sintomas aumentam durante a perman&ecirc;ncia no pr&eacute;dio (hora de trabalho) e diminuem rapidamente ao sair do pr&eacute;dio para o almo&ccedil;o e ao retornar para casa. A maioria dos sintomas, com exce&ccedil;&atilde;o dos sintomas cut&acirc;neos, melhoram nos fins de semana e desaparecem completamente nas f&eacute;rias. Enfim, a S&iacute;ndrome dos Edif&iacute;cios Doentes implica, necessariamente, em um local de trabalho desagrad&aacute;vel, com efici&ecirc;ncia de trabalho reduzida e aumento nas faltas. </p>
        <div class="subtítuloInterno">5. DOEN&Ccedil;AS, ALERGIAS E CONTAMINANTES QU&Iacute;MICOS</div>
        <p>Atualmente, uma propor&ccedil;&atilde;o cada vez maior de pessoas est&aacute; trabalhando em ambientes de escrit&oacute;rios em empregos relativamente sedent&aacute;rios. Como resultado, tem havido uma maior preocupa&ccedil;&atilde;o relacionada &agrave; exposi&ccedil;&atilde;o cr&ocirc;nica, a n&iacute;veis baixos de poluentes presentes usualmente em ambientes fechados. A resposta do trabalhador &agrave; qualidade de ar prec&aacute;ria freq&uuml;entemente resulta numa reclama&ccedil;&atilde;o de sa&uacute;de n&atilde;o espec&iacute;fica, reclama&ccedil;&atilde;o essa que raramente pode ser diretamente relacionada a um determinado agente qu&iacute;mico ou biol&oacute;gico presente no meio ambiente de escrit&oacute;rio. </p>
        <p>Dentre os poluentes analisados nesta revis&atilde;o, os compostos org&acirc;nicos vol&aacute;teis totais (COVsT) t&ecirc;m sido associados &agrave; presen&ccedil;a de odores73, irrita&ccedil;&atilde;o nos olhos, nariz e boca. Numerosos estudos investigaram o efeito na sa&uacute;de relacionados &agrave; inala&ccedil;&atilde;o de formalde&iacute;do. Segundo SAMET et al.74,o limite humano para detectar o odor desse g&aacute;s est&aacute; na faixa de 60-1200mg/m3. J&aacute; a faixa de exposi&ccedil;&atilde;o na qual foi diagnosticada irrita&ccedil;&atilde;o na garganta oscila entre 120 e 3000mg/m3 na maioria dos indiv&iacute;duos, enquanto irrita&ccedil;&atilde;o nos olhos tem sido registrada em n&iacute;veis de 100mg/m3. LEISLIE75 relata v&aacute;rios trabalhos relacionados aos efeitos do formalde&iacute;do na sa&uacute;de humana e, em particular, ao potencial carcinog&ecirc;nico dessa subst&acirc;ncia. Segundo HAYS et al.76, o grupo de estudos da OMS, respons&aacute;vel pela exposi&ccedil;&atilde;o de poluentes no ar interno, concluiu que concentra&ccedil;&otilde;es de formalde&iacute;do menores que 0,05 ppm s&atilde;o aceit&aacute;veis, enquanto que concentra&ccedil;&otilde;es maiores que 0,10 ppm s&atilde;o preocupantes. </p>
        <p>Foi comprovado que n&iacute;veis elevados de material particulado est&atilde;o associados com o decr&eacute;scimo da fun&ccedil;&atilde;o pulmonar e aumento prevalente de doen&ccedil;as respirat&oacute;rias77,78,79. Estudos realizados por DOCKERY mostraram que concentra&ccedil;&otilde;es relativamente baixas de mat&eacute;ria part&iacute;culada respir&aacute;vel t&ecirc;m sido associadas a um aumento de risco de bronquite aguda em crian&ccedil;as. Outro estudo, bastante interessante, realizado por POPE et al. 80, mostrou que a mat&eacute;ria particulada inal&aacute;vel (MPI) tem sido associada ao aumento de sintomas respirat&oacute;rios e uso de medica&ccedil;&atilde;o. Por exemplo, uma concentra&ccedil;&atilde;o de 150&micro;g/m3 de MPI durante um per&iacute;odo de 24 horas, foi associada a um aumento de 26% em sintomas respirat&oacute;rios superiores e a um aumento de 217% no uso de medica&ccedil;&atilde;o usual para asma, quando comparada com o n&uacute;mero de casos numa concentra&ccedil;&atilde;o de 50&micro;g/m3. </p>
        <p>Atualmente, j&aacute; est&aacute; mais do que provado que a exposi&ccedil;&atilde;o de n&atilde;o-fumantes &agrave; fuma&ccedil;a de tabaco (o que caracteriza o chamado fumante passivo ou involunt&aacute;rio) est&aacute; associada ao aumento de casos de doen&ccedil;as respirat&oacute;rias e decr&eacute;scimo das fun&ccedil;&otilde;es pulmonares81,82 e do crescimento. MURRY e MORRISON83 relataram um aumento de rea&ccedil;&atilde;o bronquial e da severidade de sintomas, em crian&ccedil;as com asma, que moram com m&atilde;e fumante. Recentemente, a Administra&ccedil;&atilde;o de Alimentos e Medicamentos Americana (FDA), classificou a nicotina (principal alcal&oacute;ide do cigarro) como droga, regulamentando seu uso. </p>
        <p>Devido a sua alta reatividade, os compostos oxidantes exercem um efeito bastante nocivo &agrave; sa&uacute;de. O oz&ocirc;nio, um g&aacute;s insol&uacute;vel em &aacute;gua, &eacute; conhecido por causar mudan&ccedil;as funcionais e efeitos bioqu&iacute;micos e morfol&oacute;gicos adversos &agrave;s vias respirat&oacute;rias84,85,86. J&aacute; o g&aacute;s NO2 causa efeitos similares ao oz&ocirc;nio, mas requer concentra&ccedil;&atilde;o mais elevada. Este g&aacute;s causa dano oxidativo via gera&ccedil;&atilde;o de radicais livres, que podem oxidar amino&aacute;cidos no tecido prot&eacute;ico. O NO2 tamb&eacute;m inicia a peroxida&ccedil;&atilde;o de &aacute;cidos graxos poliinsaturados nas membranas celulares do pulm&atilde;o87. </p>
        <p>Paralelamente, a n&iacute;veis baixos, o CO pode produzir sintomas n&atilde;o espec&iacute;ficos, parecidos com a gripe. BAKER et al88 observaram sintomas como dores de cabe&ccedil;a, letargia, n&aacute;usea ou desmaios em crian&ccedil;as com n&iacute;veis de carboxihemoglobina entre 2% e 10%. O n&iacute;vel normal &eacute; de 0,6%89. N&iacute;veis de at&eacute; 3% podem ser encontrados em n&atilde;o fumantes, podendo ainda ser considerados dentro do limite normal90. Segundo esses autores, n&iacute;veis entre 10 e 15% podem ser registrados ap&oacute;s fumar-se um cigarro. O poder carcinog&ecirc;nico do g&aacute;s rad&ocirc;nio &eacute; confirmado pelo consenso de opini&otilde;es de ag&ecirc;ncias de sa&uacute;de internacionais91. </p>
        <p>Enfim, j&aacute; existem muitos estudos relacionados ao efeito adverso na sa&uacute;de para v&aacute;rias classes de poluentes. Contudo, ainda h&aacute; muitas lacunas a serem preenchidas, principalmente relacionadas ao efeito sin&eacute;rgico desses poluentes na sa&uacute;de humana e a um consenso dos n&iacute;veis de exposi&ccedil;&atilde;o em ambientes n&atilde;o industriais. </p>
        <div class="subtítuloInterno">6. SINERGISMO E SENSIBILIDADE QU&Iacute;MICA M&Uacute;LTIPLA </div>
        <p>Compreender os poss&iacute;veis efeitos na sa&uacute;de associados aos contaminantes do ar em ambientes internos &eacute; fundamental para diagnosticar e remediar os problemas de qualidade do ar nestes ambientes. Todos os contaminantes analisados nesta revis&atilde;o s&atilde;o respons&aacute;veis por in&uacute;meros efeitos prejudiciais &agrave; sa&uacute;de. Contudo, existe uma consider&aacute;vel incerteza relacionada ao per&iacute;odo de exposi&ccedil;&atilde;o e concentra&ccedil;&atilde;o desses contaminantes para ocasionar problemas de sa&uacute;de espec&iacute;ficos, uma vez que o ser humano reage muito diferentemente &agrave; exposi&ccedil;&atilde;o aos poluentes. Al&eacute;m disso, do ponto de vista de diagn&oacute;stico, &eacute; muito dif&iacute;cil relacionar a exposi&ccedil;&atilde;o, nessas condi&ccedil;&otilde;es, &agrave; sintomatologia dos ocupantes dos recintos fechados. Essa &eacute; uma &aacute;rea da Epidemiologia e da Cl&iacute;nica M&eacute;dica que necessita amadurecer. </p>
        <p>O desenvolvimento de doen&ccedil;as al&eacute;rgicas em indiv&iacute;duos saud&aacute;veis &eacute; o resultado da intera&ccedil;&atilde;o entre a predisposi&ccedil;&atilde;o gen&eacute;tica para reagir com ant&iacute;genos e a exposi&ccedil;&atilde;o a fatores ambientais. Existem v&aacute;rios estudos na literatura92,93 indicando que fatores ambientais t&ecirc;m um papel fundamental no desenvolvimento de doen&ccedil;as al&eacute;rgicas em g&ecirc;meos id&ecirc;nticos. Em outras palavras, pessoas que s&atilde;o expostas a poluentes no ar interno por um per&iacute;odo de tempo mais longo s&atilde;o freq&uuml;entemente aquelas mais suscet&iacute;veis &agrave; polui&ccedil;&atilde;o em ambientes internos. Tais grupos incluem as crian&ccedil;as, os idosos, e os pacientes que sofrem doen&ccedil;as cr&ocirc;nicas, especialmente as respirat&oacute;rias e cardiovasculares. </p>
        <p>V&aacute;rios poluentes qu&iacute;micos usualmente presentes em ar de ambientes internos, tais como o benzeno e o formalde&iacute;do, s&atilde;o agentes carcinog&ecirc;nicos. Os poluentes biol&oacute;gicos podem comportar-se como patog&ecirc;nicos ou alerg&ecirc;nicos e, de acordo com seu desenvolvimento, provocam a queda de produtividade ou o absente&iacute;smo. Os ambientes fechados climatizados artificialmente t&ecirc;m como principal fonte de polui&ccedil;&atilde;o biol&oacute;gica as bandejas de condensa&ccedil;&atilde;o das m&aacute;quinas de ar condicionado. </p>
        <p>Mesmo quando os n&iacute;veis de contaminantes individuais n&atilde;o representam risco &agrave; sa&uacute;de significativo, pequenas concentra&ccedil;&otilde;es desses poluentes podem causar um efeito cl&iacute;nico em seres humanos, tendo em vista que a exposi&ccedil;&atilde;o &eacute; regular. Esse efeito sinerg&iacute;stico tem sido diagnosticado como &quot;sensibilidade qu&iacute;mica m&uacute;ltipla&quot;. </p>
        <p>A sensibilidade qu&iacute;mica m&uacute;ltipla &eacute; uma condi&ccedil;&atilde;o na qual um determinado indiv&iacute;duo &eacute; sens&iacute;vel a um n&uacute;mero espec&iacute;fico de subst&acirc;ncias qu&iacute;micas, todas em concentra&ccedil;&otilde;es muito baixas. FIEDLER et al.94 mostraram que os sintomas n&atilde;o s&atilde;o consistentes com as propriedades toxicol&oacute;gicas das subst&acirc;ncias envolvidas, nem com o n&iacute;vel de exposi&ccedil;&atilde;o. Existe muita controv&eacute;rsia relacionada &agrave; quest&atilde;o da sensibilidade qu&iacute;mica m&uacute;ltipla. Ainda se discute se existe realmente uma doen&ccedil;a f&iacute;sica, ou se ela &eacute; psicossom&aacute;tica. </p>
        <p>Recentemente, G&Oacute;RSKI et al.95 publicaram um estudo mostrando a ocorr&ecirc;ncia de um efeito sinerg&iacute;stico entre a presen&ccedil;a da fuma&ccedil;a do tabaco (fumante passivo) e concentra&ccedil;&otilde;es baixas de formalde&iacute;do (&lt;25,0-50,0mg/m3), na preval&ecirc;ncia de asma. </p>
        <div class="subtítuloInterno">7. PRESERVA&Ccedil;&Atilde;O E CONSERVA&Ccedil;&Atilde;O</div>
        <p>Al&eacute;m dos problemas de sa&uacute;de, existe tamb&eacute;m o problema da deteriora&ccedil;&atilde;o de obras de arte e liter&aacute;rias pelos contaminantes presentes no ar. Os principais agentes de deteriora&ccedil;&atilde;o de acervo documental s&atilde;o: umidade e temperatura, insetos, fungos e roedores, polui&ccedil;&atilde;o ambiental e ilumina&ccedil;&atilde;o96-100. </p>
        <p>Os materiais org&acirc;nicos em geral, especialmente os de origem natural, como o papel, o couro e o pergaminho, necessitam de uma determinada quantidade de &aacute;gua em sua estrutura molecular. Em ambientes &uacute;midos, como na maior parte do Brasil, estes materiais tendem a absorver &aacute;gua. O excesso de umidade favorece a combina&ccedil;&atilde;o com poluentes atmosf&eacute;ricos, formando &aacute;cidos, que por sua vez promovem rea&ccedil;&otilde;es de hidr&oacute;lise da celulose. O desenvolvimento de microorganismos, respons&aacute;veis pela deteriora&ccedil;&atilde;o biol&oacute;gica, tamb&eacute;m est&aacute; ligado a essas condi&ccedil;&otilde;es. </p>
        <p>Dentre os poluentes mais agressivos &agrave;s obras, destacam-se a poeira101,102. 103, o g&aacute;s oz&ocirc;nio104 e os &oacute;xidos &aacute;cidos gerados a partir da queima de combust&iacute;veis (NOx, SOx ). A deposi&ccedil;&atilde;o cont&iacute;nua da poeira sobre os documentos prejudica a est&eacute;tica das pe&ccedil;as, favorece o desenvolvimento de microorganismos e pode acelerar a deteriora&ccedil;&atilde;o do material arquiv&iacute;stico devido aos &aacute;cidos nele contidos105a-b. Por outro lado, os &oacute;xidos &aacute;cidos agridem mais rapidamente a estrutura qu&iacute;mica dos materiais construtivos das pe&ccedil;as do acervo. </p>
        <p>A luz, natural ou artificial, &eacute; um tipo de radia&ccedil;&atilde;o eletromagn&eacute;tica capaz de produzir altera&ccedil;&otilde;es f&iacute;sico-qu&iacute;micas na estrutura dos materiais usualmente utilizados na confec&ccedil;&otilde;es de documentos, induzindo a um processo de envelhecimento acelerado106. As radia&ccedil;&otilde;es s&atilde;o classificadas de acordo com seus comprimentos de onda. Desse modo, a radia&ccedil;&atilde;o ultravioleta situa-se entre 200 e 400 nm, a radia&ccedil;&atilde;o vis&iacute;vel entre 400 e 700 nm e a infravermelha acima de 700 nm. Embora as tr&ecirc;s radia&ccedil;&otilde;es mencionadas sejam potencialmente agressivas &agrave; documenta&ccedil;&atilde;o gr&aacute;fica, os mecanismos de fotodegrada&ccedil;&atilde;o s&atilde;o diferentes, devido &agrave;s diferen&ccedil;as de energia envolvidas, correspondentes aos comprimentos de onda107. A deteriora&ccedil;&atilde;o fotoqu&iacute;mica depende de diversos fatores como, por exemplo, a faixa de comprimento de onda, a intensidade de radia&ccedil;&atilde;o, e o tempo de exposi&ccedil;&atilde;o e natureza qu&iacute;mica do material documental (papel, pergaminho, couro, etc. ). </p>
        <p>Em resumo, a presen&ccedil;a de contaminantes qu&iacute;micos pode danificar o material art&iacute;stico e bibliogr&aacute;fico mantido em museus e bibliotecas espalhadas pelo Brasil. </p>
        <div class="subtítuloInterno">8. EDUCA&Ccedil;&Atilde;O E CONSCI&Ecirc;NCIA AMBIENTAL DA POPULA&Ccedil;&Atilde;O </div>
        <p>A educa&ccedil;&atilde;o, no contexto sugerido por essa se&ccedil;&atilde;o, est&aacute; limitada &agrave; divulga&ccedil;&atilde;o de informa&ccedil;&otilde;es, para os ocupantes de pr&eacute;dios e resid&ecirc;ncias, da exist&ecirc;ncia de poluentes no ar de interiores e a import&acirc;ncia de se entender os mecanismos/a&ccedil;&otilde;es que os ocupantes podem realizar a fim de reduzir, ou mesmo eliminar, contaminantes geralmente encontrados em ambientes fechados. </p>
        <p>A literatura est&aacute; repleta de estudos indicando que a maioria dos pr&eacute;dios em que ocorrem reclama&ccedil;&otilde;es dos ocupantes, procedimentos de manuten&ccedil;&atilde;o inadequados, tais como filtros de ar condicionado sujos ou mesmo inexistentes, dutos e bandejas de ar condicionado sujos, e fotocopiadoras sem sistema pr&oacute;prio de exaust&atilde;o t&ecirc;m sido o motivo principal do desconforto. </p>
        <p>O conhecimento, pelos ocupantes desses ambientes, de situa&ccedil;&otilde;es que poderiam contribuir para o aumento das concentra&ccedil;&otilde;es de agentes qu&iacute;micos e biol&oacute;gicos em recintos fechados, possibilitaria uma remedia&ccedil;&atilde;o mais efetiva por parte do pessoal encarregado da manuten&ccedil;&atilde;o do pr&eacute;dio, ou do propriet&aacute;rio da resid&ecirc;ncia. Nos &uacute;ltimos anos, t&ecirc;m ocorrido in&uacute;meras reportagens abordando a problem&aacute;tica da polui&ccedil;&atilde;o do ar de interiores, realizadas pela imprensa falada e escrita108,109.</p>
        <p>Contudo, a disponibilidade de informa&ccedil;&otilde;es para o p&uacute;blico leigo n&atilde;o fornece nenhuma garantia de que a informa&ccedil;&atilde;o ser&aacute; utilizada. O uso da informa&ccedil;&atilde;o depender&aacute; da motiva&ccedil;&atilde;o do indiv&iacute;duo e disponibilidade de a&ccedil;&atilde;o, pois muitas das vezes os ocupantes de pr&eacute;dios comerciais n&atilde;o possuem nenhum controle sobre o seu ambiente de trabalho. Logo, o simples conhecimento das poss&iacute;veis causas de desconforto e habilidade de detectar poss&iacute;veis fontes possibilitaria ao ocupante esclarecido exercer press&otilde;es junto ao setor respons&aacute;vel pela manuten&ccedil;&atilde;o do seu local de trabalho. Por exemplo, a press&atilde;o para a pr&aacute;tica de simples padr&otilde;es de higiene pessoal, tais como dar descarga no toalete ap&oacute;s uso, pode reduzir a contamina&ccedil;&atilde;o por agentes microbiol&oacute;gicos gerados por atividades humanas. Al&eacute;m disso, os ocupantes podem pressionar os respons&aacute;veis pela manuten&ccedil;&atilde;o do pr&eacute;dio a seguir os padr&otilde;es m&iacute;nimos de ventila&ccedil;&atilde;o e limpeza no sistema de circula&ccedil;&atilde;o mec&acirc;nico do ar, pr&aacute;ticas essas que minimizam o potencial de contamina&ccedil;&atilde;o qu&iacute;mica e biol&oacute;gica. </p>
        <p>Essa educa&ccedil;&atilde;o pode ter a forma de informa&ccedil;&otilde;es gerais atrav&eacute;s de cartilhas, palestras e v&iacute;deos, elaborados numa linguagem simples e rica, com exemplos de maneiras de detectar e remediar as fontes mais comuns de polui&ccedil;&atilde;o do ar em recintos fechados. Da mesma maneira, o pessoal ligado &agrave; manuten&ccedil;&atilde;o do pr&eacute;dio deve ser treinado para entender aspectos da QAI na rotina de seu trabalho. Muitas atividades de manuten&ccedil;&atilde;o afetam diretamente a QAI, e algumas podem ocasionar problemas graves. Logo, os ocupantes devem estar conscientes dos aspectos b&aacute;sicos da QAI e de como suas atividades podem ter um impacto direto na sua sa&uacute;de e conforto. </p>
        <div class="subtítuloInterno">9. PERSPECTIVAS</div>
        <p>A QAI &eacute; uma &aacute;rea de pesquisa emergente no Brasil, e ainda existem in&uacute;meras lacunas a serem preenchidas. Dentre os assuntos que merecem aten&ccedil;&atilde;o futura est&atilde;o: </p>
        <p>&bull; A avalia&ccedil;&atilde;o qu&iacute;mica e microbiol&oacute;gica de ambientes residenciais, escolares, hospilares e de lazer. Dentre esses ambientes, o residencial merece aten&ccedil;&atilde;o especial, uma vez que &eacute; o local no qual a maioria das pessoas passa grande parte do seu tempo. </p>
        <p>&bull; A necessidade de implanta&ccedil;&atilde;o de metodologias anal&iacute;ticas para outros tipos de contaminantes usualmente encontrados em tais ambientes. Dentre os principais contaminantes que precisam ter metodologia implantada no Brasil, est&atilde;o o oz&ocirc;nio, NO2 e outros gases oxidantes, rad&ocirc;nio, compostos org&acirc;nicos semi-vol&aacute;teis, micotoxinas, endotoxinas e al&eacute;rgenos de microorganismos e &aacute;caros dom&eacute;sticos. </p>
        <p>&bull; Avalia&ccedil;&atilde;o, em n&iacute;vel nacional, da QAI. As pesquisas at&eacute; agora realizadas est&atilde;o concentradas no eixo Rio-S&atilde;o Paulo. Com a implanta&ccedil;&atilde;o do Programa de Qualidade do Ar de Interiores no CESTEH - ENSP - FIOCRUZ espera-se a ades&atilde;o de outros grupos no pa&iacute;s, com o intuito de fazer um levantamento mais abrangente das condi&ccedil;&otilde;es ambientais em tais sistemas, em &acirc;mbito nacional. Seria, tamb&eacute;m, extremamente importante, a participa&ccedil;&atilde;o de profissionais especializados em engenharia de ar condicionado, arquitetura e urbanismo, sa&uacute;de p&uacute;blica, epidemiologia, toxicologia, cat&aacute;lise, e fotoqu&iacute;mica da atmosfera. </p>
        <p>&bull; Levantamento estat&iacute;stico dos dados ligados &agrave; quest&atilde;o da QAI. O atual est&aacute;gio de desenvolvimento da QAI no Brasil n&atilde;o permite nenhum estudo estat&iacute;stico relacionando os problemas de sa&uacute;de &agrave; baixa qualidade do ar respirado em locais fechados. Espera-se que futuros trabalhos apresentem uma avalia&ccedil;&atilde;o epidemiol&oacute;gica junto com o monitoramento qu&iacute;mico e microbiol&oacute;gico. </p>
        <p>&bull; A implanta&ccedil;&atilde;o e consolida&ccedil;&atilde;o de uma estrutura legislativa fundamentada em estudos sistem&aacute;ticos e com o consenso de opini&otilde;es de autoridades cient&iacute;ficas que atuem em diferentes &aacute;reas de pesquisa. Provavelmente, a melhor solu&ccedil;&atilde;o seria a cria&ccedil;&atilde;o de um grupo, sem v&iacute;nculo com o governo federal, para coordena&ccedil;&atilde;o de assuntos relacionados &agrave; legisla&ccedil;&atilde;o, junto aos minist&eacute;rios governamentais competentes (Minist&eacute;rio do Trabalho e da Sa&uacute;de). Talvez, a BRASINDOOR possa servir de elo entre a comunidade cient&iacute;fica e as autoridades governamentais. </p>
        <p>&bull; Estudo da din&acirc;mica de poluentes e a varia&ccedil;&atilde;o de par&acirc;metros f&iacute;sicos, assim como o estudo cin&eacute;tico da reatividade de contaminantes no ar de ambientes internos. </p>
        <p>&bull; A cria&ccedil;&atilde;o de um banco de dados de emiss&atilde;o de COVs por produtos produzidos no pa&iacute;s. Isto pode servir de base para orientar a ind&uacute;stria e os consumidores no sentido de utilizar materiais com n&iacute;veis de emiss&otilde;es reduzidos. </p>
        <p>Esses s&atilde;o apenas alguns exemplos do muito a ser realizado pela Qu&iacute;mica, em benef&iacute;cio da QAI. Um programa de Qualidade do Ar de Interiores bem estruturado pode servir como uma das v&eacute;rtice de um programa de medicina preventiva no pa&iacute;s. </p>
        <div class="subtítuloInterno">AGRADECIMENTOS </div>
        <p>Agradecemos ao FINEP e FUJB pelo suporte financeiro a este trabalho. Dra. L. S. Brickus agradece ao CNPq a concess&atilde;o de uma bolsa de doutorado. </p>
        <div class="subtítuloInterno">REFER&Ecirc;NCIAS </div>
        <p>1. Turiel, I.; Hollowell, C. D.; Miksch, R. R.; Rudy, J. V.; Young, R. A.; Coye, M. J.; Atmos. Environ. <strong>1983</strong>, 17, 51.&nbsp;&nbsp;&nbsp;&nbsp; <br>
            2. a) H&ouml;ppe, P. R.; Experientia <strong>1993</strong>, 49, 775.;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
            b) Peterson, F.; Wennerstr&ouml;m, J.; Grana <strong>1991</strong>, 30, 395.;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
            c) Finnegan, M. J. , Pickering, C. A. C. , Burge, P. S.; Brit. Med. J. <strong>1984</strong>, 289, 1573.;<br>
            d) Skov, P.; Valbjorn, O.; Pedersen, B. V.; Scand. J. Work Environ. Health <strong>1989,</strong> 15, 286.;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
            e) Rudnai, P.; S&aacute;rk&aacute;ny, E.; B&aacute;nhidi, L.; Gereben, Z.; B&aacute;cskai, J.; Kert&eacute;sz, M.; Martini, F.; Selmeczy, K. H.; Proceedings of the 3rd International Conference: Healthy Buildings'94, Budapest <strong>1994,</strong> 1, 487.;&nbsp;&nbsp;&nbsp; <br>
            f) Walkinshaw, D. S.; Atmos. Environ. <strong>1992</strong>, 26A, 2137.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>3. Kirchner, S.; Karpe, P.; Proceedings of the 7th Int. Conf. on Indoor air Quality and Climate., Nagoya <strong>1996</strong>, 2, 663.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>4. Wallance, L. A.; Pellizzari, E. D.; Leader, B.; Zelon, H.; Sheldon, L.; Atmos. Environ. <strong>1987</strong>, 21, 385.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>5. Fioravanti, C.; Globo Ci&ecirc;ncia <strong>1995,</strong> Abril, 36.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>6. Miguel, A. H.; Aquino Neto, F. R.; Cardoso, J. N.; Vasconcellos, P. C.; Pereira, A. S.; Marquez, K. S. G.; Environ. Sci. Technol. <strong>1995</strong>, 29, 338.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>7. Santos, C. Y.; Aquino Neto, F. R.; Cardoso, J. N.; Indoor + Built Environ. , aceito.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>8. Miguel, A. H.; Pedreira Filho, W. R.; Allen, A. G.; Indoor Air <strong>1995</strong>, 4, 355.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>9. Rocha, L. S.; Aquino Neto, F. R.; Cardoso, J. N.; Resumos da 19a Reuni&atilde;o Anual da SBQ, AB-09, Minas Gerais, Brasil, 1996.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>10. Brickus, L. S., Cardoso, J. N. and Aquino Neto, F. R.; Proceedings of the 5rd International Conference: Healthy Buildings'97, Washington, D. C., USA. Aceito. <strong>1997</strong>, 2, 47.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>11. Rocha, L. S.; Tese de Doutorado. Instituto de Qu&iacute;mica, UFRJ, 1997&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>12. Oliveira, C. J.; Disserta&ccedil;&atilde;o de Mestrado. Instituto de Qu&iacute;mica, UFRJ, em prepara&ccedil;&atilde;o.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>13. Pereira, F. O. R.; de Souza, M. B.; Proceedings of the 7th Int. Conf. on Indoor air Quality and Climate., Nagoya <strong>1996,</strong> 1, 377.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>14. Malanca, A.; Pessina, V.; Dallara, G.; Radiat. Prot. Dosim. <strong>1993</strong>, 48, 199.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>15. Urban, M.; Sicherheit, H.; Estrada, J. J.; Binns, D. A. C.; Internal. Report of KFK., Karlsruhe, Germany KFK 3866 and CNEN - Brazil n 1101: p. 68.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>16. Shuguang, L.; Dinhua, P.; Guoxiong, W.; Arch. Environ. Health <strong>1994</strong>, 49, 119.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>17. Thi&eacute;baud, H. P.; Knize, M. G.; Kuzmicky, P. A.; Felton, J. S.; Hsieh, D. P.; J. Agric. Food Chem. <strong>1994</strong>, 42, 1502.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>18. Batterman, S.; Peng, C.; Am. Ind. Hyg. Assoc. J. <strong>1995</strong>, 56, 55.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>19. Weschler, C. J.; Shields, H. C.; Rainer, D.; Am. Ind. Hyg. Assoc. J.<strong> 1990,</strong> 51, 261.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>20. Whillans, F. D.; (1996). Proceedings of the 7th Int. Conf. on Indoor air Quality and Climate., Nagoya <strong>1996,</strong> 3, 1043.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>21. Shah, J. J; Singh, H. B.; Environ. Sci. Technol. <strong>1988</strong>, 22, 1381.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>22. Sextro, R. G.; Atmos. Environ.<strong> 1987,</strong> 21, 431.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>23. Wahlstrom, J.; Calderon, J.; Striefel, A.; Johnson, B.; Blumenthal, M.; J. Allergy Clin. Immunol.<strong> 1989,</strong> 83, 266.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>24. D'amato, G.; Spieksma, F. Th. M.; Allergy <strong>1995,</strong> 50, 870.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>25. Salvaggio, J. E.; Burge, H. A.; Chapman, J. A.; J. Allergy Clin. Immunol.<strong> 1993</strong>, 92, 217.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>26. Platts-Mills, T. A. E.; Heymann, P. W. .; Longbottom, J. L.; Wilkins, S. R.; J. Allergy Clin. Immunol.<strong> 1986</strong>, 77, 850.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>27. Owen, M. K. , Ensor, D. S. , Sparks, L. E.; Atmos. Environ. <strong>1992</strong>, 26, 2149.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>28. Oie, S.; Masumoto, N.; Hironaga, K.; Koshiro, A.; Kamiya, A.; Microbios<strong> 1992,</strong> 72, 161.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>29. Nazaroff, W. W.; Cass,G. R.; Atmos. Environ.,<strong> 1991,</strong> 25A, 841.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>30. Hassen, N. G.; Ghosh,T. K.; Hines, A. L.; Loyalka, S. K.; Sep. Science Technol.<strong> </strong><strong>1992</strong>, 27, 1955.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>31. Stone, R.; Science <strong>1994</strong>, 263, 465.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>32. Helmig, D.; Arey, J.; Intern. J. Environ. Anal. Chem.<strong> 1991</strong>, 43, 219.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>33. Reisch, M. S.; Chem. &amp; Eng. <strong>1994,</strong> october 3, 44.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>34. Cailleux, A., Bouchara, J. P., Daniel, V., Chabasse, D., Allain, P.; Chromatographia <strong>1992</strong>, 34, 613.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>35. Wilkes, C. R.; Small, M. J.; Anderlman, J. B.; Giardino, N. J.; Marshall, J.; Atmos. Environ. <strong>1992</strong>, 26A, 2227.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>36. Sack, T. M.; Steele, D. H.; Remmers, J.; Atmos. Environ. <strong>1992</strong>, 26A, 1063.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>37. Neumeister, H. G.; M&ouml;ritz, M.; Schleibinger, H.; Martiny, H.; Proceedings of the 7th Int. Conf. on Indoor air Quality and Climate. , Nagoya <strong>1996</strong>, 3, 125.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>38. Wolkoff,P.; Wilkins, C. K.; Clausen, P. A.; Larsen, K.; Indoor air <strong>1993,</strong> 3, 113.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>39. Keating, G. A.; Mckone, T. E.; Gillett, J. W.; Atmos. Environ. <strong>1997</strong>, 31, 123.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>40. Kamens, R.; Odum, J.; Fan, Z. H.; Environ. Sci. Technol. <strong>1995</strong>, 29, 43.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>41. Rosell, A.; Grimalt, J. O.; Rosell, M. G.; Guardino, X.; Albaig&eacute;s, J.; Fres. J. Anal. Chem.<strong> 1991</strong>, 339, 689.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>42. Valerio, F.; Pala, M.; Fres. J. Anal. Chem<strong>. 1991,</strong> 339, 777.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>43. Pitts, J. N., Van Cauwenberghe, K. A.; Grosjean, D.; Schmid, J. P.; Fitz, D. R.; Belser, W. L.; Knudson, G. B.; Hynds, P. M.; Science<strong> 1978</strong>, 202, 515.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>44. Koo, L. C.; Matsushita, H.; Ho, J. H. C.; Wong, M. C.; Shimizu, H.; Mori, T.; Matsuki, H.; Tominaga, S.; Environ. Tech. <strong>1994,</strong> 15, 401.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>45. Guerin, M. R.; Jenkins, R. A.; Tomkins, B. A.; The chemistry of environmental tobacco smoke: Composition and measurement.; Boca Raton Lewis Pibl.; 1992; p. 230.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>46. Rogge, W. F.; Hildemann, L. M.; Mazurek, M. A.; Cass, G. R.; Simoneit, B. R. T.; Environ. Sci. Technol. <strong>1994</strong>, 28, 1375.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>47. Benner, C. L.; Bayona, J. M.; Caka, F. M.; Tang, H.; Lewls, L.; Crawford, J.; Lamb, J. D.; Lee, M. L.; Lewis, E. A.; Hansen, L. D.; Eatough, D. J.; Environ. Sci. Technol.<strong> 1989</strong>, 23, 688.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>48. Davies, R. J., Sheinmann, B. D.; J. Allergy Clin. Immunol.<strong> 1986,</strong> 78, 1031.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>49. Guerin, M. R.; Jenkins, R. A.; Tomkins, B. A.; The chemistry of environmental tobacco smoke: Composition and measurement.; Boca Raton Lewis Pibl.; 1992; p. 230.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>50. Eatough, D. J.; Benner, C. L., Bayona, J. M., Caka, F. M., Mooney, R. L., Lamb, J. D., Lee, M. L., Lewis, E. A., Hansen, L. D., Eatough, N. L.; Proceedings of the 4th International Conference on Indoor Air Quality and Climate<strong> 1987</strong>, Berlin (West), p. 17.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>51. ASTM- American Society for Testing and Material (1990) Standard test method for nicotine in indoor air. In: Annual book of ASTM standards. D5075-90a&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>52. Brimblecombe, P.; Atmos. Environ. <strong>1990</strong>, 24B, 1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>53. Zhang, J.; Wilson, W. E.; Lioy, P. J.; Environ. Sci. Technol<strong> 1994,</strong> 28, 1975.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>54. Weschler, C. J.; Hodgson, A. T.; Wooley, J. D.; Environ. Sci. Technol<strong>. 1992</strong>, 26, 2371.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>55. Hansen, T. B.; Andersen, B.; Am. Ind. Hyg. Assoc. J. <strong>1986</strong>, 47, 659.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>56. Andersson, B.; Andersson, K.; Nilsson, C. A.; Sandstr&ouml;m, M.; Sjernberg, N.; Sundell, J.; Proceedings of the 7th Int. Conf. on Indoor air Quality and Climate., Nagoya <strong>1996,</strong> 3, 947.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>57. Pitts Jr. , J. N.; Klan, A. U.; Smith, E. B.; Wayne, R. P.; Environ. Sci. Technol. <strong>1969</strong>, 3, 241.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>58. Samet, J. M.; Lambert, W. E.; Skipper, B. J.; Cushing, A. H.; Hunt, W. C.; Young, S. A.; Mclaren, L. C.; Schwab, M.; Spengler, J. D.; Am. Rev. Respir. Dis<strong> 1993</strong>, 148, 1258.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>59. a) Weschler, C. J.; Brauer, M.; Koutrakis, P.; Environ. Sci. Technol. <strong>1992</strong>, 26, 179.;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; b) Weschler, C. J.; Shields, H. C.; Naik, D. V.; Environ. Sci. Technol. <strong>1994,</strong> 28, 2120. </p>
        <p>60. Vecera, Z.; Dasgupta, P. K. Int. J. Environ. Anal. Chem. <strong>1994</strong>, 56, 311.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>61. Brickus, L. S., Cardoso, J. N. and Aquino Neto, F. R.; Proceedings of the 5rd International Conference: Healthy Buildings'97, Washington, D. C., USA.<strong> 1997</strong>, 2, 53.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>62. Chan, C. C.; &Ouml;zkaynak, H.; Spengler, J. D.; Sheldon, L.; Environ. Sci. Technol. <strong>1991</strong>, 25, 964.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>63. Carter, W. P. L.; Pierce, J. A.; Luo, D.; Malkina, I. L.; Atmos. Environ.<strong> 1995,</strong> 29, 2499.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>64. Perry, R.; Gee, I. L.; Indoor Environ. <strong>1994,</strong> 3, 224.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>65. Field, R. A.; Philipps, J. L.; Goldstone, M. E.; Lester, J. N.; Perry, R.; Environ. Technol. <strong>1992</strong>, 13, 391.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>66. Daisey, J. M.; Miguel, A. H.; de Andrade, J. B.; Pereira, P. A. P.; Tanner, R. L.; JAPCA <strong>1987</strong>, 37, 15.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>67. Forti, M. C.; Moreira-Nordemann, L. M.; Andrade, M. F.; Oesini, C. Q.; Atmos. Environ. <strong>1990</strong>, 24B, 355.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>68. Allen, A. G.; Miguel, A. H.; Atmos. Environ. <strong>1995,</strong> 29, 3519.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>69. a)Tanner, R. L.; Miguel, A. H.; de Andrade, J. B.; Gaffeney, J. S.; Streit, G. E.; Environ. Sci. Technol<strong>. 1988</strong>, 22, 1026.;<br>
            b) Grosjean, D.; Miguel, A. H.; Tavares,T. M.; Atmos. Environ. <strong>1990</strong>, 24B, 101.;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
            c)Miguel, A. H.; de Andrade, J. B.; Carneiro, M. C.; Cardoso, J. N.; Coelho, L. B.; Castelli,&nbsp;&nbsp;&nbsp;&nbsp; A. S.; Szwarc, A.; Branco, G.; Proceedings II Symp. Automotive Eng. , Bras&iacute;lia, Brazil, 1985, p. 421.; de Andrade, J. B.; Miguel, A. H.; Intern. J. Environ. Anal. Chem. <strong>1985</strong>, 21, 229.; d) de Andrade, J. B.; Miguel, A. H.; Qu&iacute;m. Nova <strong>1985</strong>, 8, 356.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>70. Miguel, A. H.; Environ. Sci. Technol.<strong> </strong><strong>1991,</strong> 25, 590.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>71. Molhave, L.; Ann. N. Y. Acad. Sci. <strong>1992,</strong> 641, 46.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>72. Robertson, A. S.; Burge, P. S.; Hedge, A.; Sims, J.; Gill, F. S.; Finnegan, M.; Pickering, C. A. C.; Dalton, G.; Brit. Med. J.<strong> 1985,</strong> 291, 373. </p>
        <p>73. Kirchner, S.; Karpe,P. Proceedings of the 7th Int. Conf. on Indoor air Quality and Climate., Nagoya <strong>1996</strong>, 2, 663.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>74. Samet, J. M.; Marbury, M. C.; Spengler, J. D.; Am. Rev. Respir. Dis. <strong>1988,</strong> 137, 221.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>75. Leslie, G. B.; Indoor Built Environ.<strong> 1996,</strong> 5, 132.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>76. Hays, S. M.; Gobbell, R. V.; Ganick, N. R.; Indoor Air Quality: Solutions and strategies; McGram-Hill, Inc.; 1995; p. 70.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>77. Ware, J. H.; Ferrin, Bg; Dockery, Dw; Spengler, Jd; Stram, Do; Speizer, F. E.; Am. Rev. Respir. Dis. <strong>1986,</strong> 33, 834.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>78. Dockery, D. W., Speizer, F. E., Stram, D. O., Ware, J. H., Spengler, J. D., Ferris, B. G. Jr.; Am. Rev. Respir. Dis.<strong> 1989,</strong> 139, 587. </p>
        <p>79. Schwartz, J.; Environ. Res<strong>. 1991</strong>, 56, 204. </p>
        <p>80. Pope, C. A. III; Dockery, D. W.; Spengler, J. D.; Raizenne, M. E.; Am. Rev. Respir. Dis. <strong>1991,</strong> 144, 668.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>81. Emmons, K. M., Abrams, D. B., Marshall, R., Marcus, B. H., Kane, M., Novotny, T. E., Etzel, R. A.; Prev. Med.<strong> 1994</strong>, 23, 35.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>82. Repace, J. L.; Lowrey, A. H.; Science <strong>1980,</strong> 208, 464.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>83. Murray, A. B.; Morrison,B. J.; J. Allergy Clin. Immunol<strong>. 1986,</strong> 77, 575.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>84. Graham, D.; Henderson, F.; House, D.; Arch. Environ. Health, <strong>1988</strong>, 43, 228.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>85. Virant, F.; Baker, C.; Koenig, J.; Marshall, S.; Williams, P.; Mcmanus, M.; Luchtel, D.; Altman, L.; J. Allergy Clin. Immunol.<strong> 1989</strong>, 83, 176.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>86. Williams, P. V.; Mcbride, D. E.; Koenig, J. O.; Henderson, W. R.; Pirson, W. E.; J. Allergy Clin. Immunol. <strong>1992,</strong> 89, 230.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>87. Alberts, W. M.; J. Allergy Clin. Immunol. <strong>1994</strong>, 94, 289.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>88. Baker, M. D.; Henretig, F. M.; Ludwig, S.; J. Pediatr. <strong>1988</strong>, 113, 501.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>89. Gold, D. R.; Clin. Chest Med. <strong>1992,</strong> 13, 215.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>90. Ilano, A. L.; Raffin, T. A. Chest <strong>1990</strong>, 97, 165.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>91. Samet, J. M.; J. Natl. Cancer Inst. <strong>1989</strong>, 81, 745.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>92. Lubs, M. K. E.; Acta Allergol. <strong>1971</strong>, 26, 249.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>93. W&uuml;trich, B.; Baumann, E.; Fries, R. A.; Schnyder, E. W. Clin. Allergy,<strong> 1981,</strong> 11,47.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>94. Fiedler, N.; Maccic, C.; Kipen, H.; J. Occup. Med<strong>. 1992</strong>, 43, 529.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>95. G&oacute;rski, P.; Palczynski, C.; Hanke, W.; Stankiewicz, J.; Kolacinska, B.; Ruta, U; Gruchala, J.; Krakowiak, A.; Szulc, B.; Jakubowski, J.; Gromiec, P.; Brzeznicki, S.; Wesolowski, W.; Proceedings of the 7th International Conference on Indoor air quality and climate, Nagoya <strong>1996,</strong> 1, 173.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>96. Bogaty, H.; Campbell, K. S.; Appel, W. D.; Text. Res. J.<strong> 1952</strong>, 22, 81.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>97. Druzik, J. R.; Adams, M. S.; Tiller, C.; Cass, G. R.; Atmos. Environ. <strong>1990,</strong> 24A, 1813.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>98. Jaffe, L. S.; J. Air Pollut. Control. Assoc. <strong>1967,</strong> 17, 375.</p>
        <p>99. Kattai, A. A.; Schuerch, C.; J. Polymer Sci. Part A-1 <strong>1966,</strong> 4, 2683.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>100. Whitmore, P. M.; Cass, G. R.; Druzik, J. R.; J. Amer. Inst. Conserv. <strong>1987,</strong> 26, 45.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>101. Baer, N. S.; Banks, P. N.; Int. J. Mus. Manag. Curatorship <strong>1985</strong>, 4, 9.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>102. Ligocki, M. P.; Salmon, L. G.; Fall, T.; Jones, M. C. ; Nazaroff, W. W.; Cass, G. R.; Atmos. Environ. <strong>1993</strong>, 27A, 697.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>103. Nazaroff, W. W.; Salmon, L. G.; Cass, G. R.; Environ. Sci. Technol. <strong>1990</strong>, 24, 66.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>104. Lee, D. S.; Holland, M. R.; Falla, N.; Atmos. Environ. <strong>1996,</strong> 30, 1053.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>105. a) Lafontaine,R. H.; Tech. Bull. <strong>1978</strong>, 3, 1.;&nbsp;&nbsp; <br>
            &nbsp;b) Lafontaine, R. H.; Tech. Bull.<strong> 1979</strong>, 5, 1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>106. Luccas, L.; Seripierri, D.; Conservar para n&atilde;o restaurar- Uma proposta para preserva&ccedil;&atilde;o de documentos em bibliotecas.; ed. Thesaurus. 1994, p 19.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>107. Beck, I.; Manual de preserva&ccedil;&atilde;o de documentos.; Minist&eacute;rio da Justi&ccedil;a, Arquivo Nacional, Rio de Janeiro, ed. Funda&ccedil;&atilde;o Vitae, 1991, p. 3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>108. Anon.; Projeto <strong>1995,</strong> 183, 6.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>109. Anon.; Facility <strong>1997</strong>, 1, 26.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>&nbsp; </p>
        <p>&nbsp; </p>
        <p># Endere&ccedil;o atual: Funda&ccedil;&atilde;o Oswaldo Cruz - ENSP - CESTEH - Rua Leopoldo Bulh&otilde;es, 1480 - 21041-210 - Manguinhos - Rio de Janeiro - RJ<br>
            E-mail: lbrickus@ensp. fiocruz. br </p>
        <p>&nbsp;<br>
            &copy; 2007&nbsp; SBQ</p>
        <p>Secretaria Executiva<br>
            Av. Prof. Lineu Prestes, 748 - bloco 3 - Superior<br>
            05508-000 S&atilde;o Paulo SP - Brazil<br>
            C.P. 26.037 - 05599-970<br>
            Tel.: +55 11 3032.2299<br>
            Fax: +55 11 3814.3602</p>
        <p>&nbsp;</p>
        <p>sbqsp@quim.iq.usp.br</p>
    </div>
</div>

<?php include 'footer.php'; ?>